#include <stdio.h>

#include <erl_nif.h>

int main()
{

	printf("// This file is automatically generated by nifconf_gen.  Do not edit or commit.\n\n");

	// version
	printf("pub const ERL_NIF_MAJOR_VERSION: Uint = %d;\n", ERL_NIF_MAJOR_VERSION);
	printf("pub const ERL_NIF_MINOR_VERSION: Uint = %d;\n", ERL_NIF_MINOR_VERSION);
	printf("pub const ERL_NIF_MIN_REQUIRED_MAJOR_VERSION_ON_LOAD: Uint = %d;\n", ERL_NIF_MIN_REQUIRED_MAJOR_VERSION_ON_LOAD);

	// scheduler
#ifdef ERL_NIF_DIRTY_SCHEDULER_SUPPORT
	printf("pub const ERL_NIF_DIRTY_SCHEDULER_SUPPORT: bool = true;\n");
	printf("pub const ERL_DRV_DIRTY_JOB_CPU_BOUND: Uint = %d;\n", ERL_DRV_DIRTY_JOB_CPU_BOUND);
	printf("pub const ERL_DRV_DIRTY_JOB_IO_BOUND: Uint = %d;\n", ERL_DRV_DIRTY_JOB_IO_BOUND);
#else
	printf("pub const ERL_NIF_DIRTY_SCHEDULER_SUPPORT: bool = false;\n");
#endif

	// types
	switch(sizeof(ERL_NIF_TERM)) {
	case 4:
		printf("type erl_term = u32;\n");
		break;
	case 8:
		printf("type erl_term = u64;\n");
		break;
	}

	switch(sizeof(int)) {
	case 4:
		printf("type Int = i32;\n");
		printf("type Uint = u32;\n");
		break;
	case 8:
		printf("type Int = i64;\n");
		printf("type Uint = u64;\n");
		break;
	}

	return 0;
}