[package]
name = "rustler"
description = "Safe Rust wrappers for creating Erlang NIF functions"
repository = "https://github.com/rusterlium/rustler"
version = "0.36.2" # rustler version
authors = ["Hansihe <me@hansihe.com>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
edition = "2021"
rust-version = "1.70"

[features]
big_integer = ["dep:num-bigint"]
default = ["nif_version_2_15"]
derive = []
allocator = []
nif_version_2_14 = []
nif_version_2_15 = ["nif_version_2_14"]
nif_version_2_16 = ["nif_version_2_15"]
nif_version_2_17 = ["nif_version_2_16"]
serde = ["dep:serde"]

[dependencies]
inventory = "0.3"
rustler_codegen = { path = "../rustler_codegen", version = "0.36.2"}
num-bigint = { version = "0.4", optional = true }
serde = { version = "1", optional = true }

[target.'cfg(not(windows))'.dependencies]
libloading = "0.8"

[build-dependencies]
regex-lite = "0.1"

[package.metadata.release]

[[package.metadata.release.pre-release-replacements]]
file = "../rustler_mix/mix.exs"
search = "version: \"[^\"]+\", # Auto updated by cargo release, do not modify this line."
replace = "version: \"{{version}}\", # Auto updated by cargo release, do not modify this line."

[[package.metadata.release.pre-release-replacements]]
file = "../rustler_mix/lib/rustler.ex"
search = "def rustler_version, do: \"[^\"]+\""
replace = "def rustler_version, do: \"{{version}}\""

[[package.metadata.release.pre-release-replacements]]
file = "../rustler_codegen/Cargo.toml"
search = "# rustler_codegen version\nversion = \"[^\"]+\""
replace = "# rustler_codegen version\nversion = \"{{version}}\""

[package.metadata.docs.rs]
all-features = true
